name: Execute Jest Unit Test

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
      - name: install node moudles
        run: npm install
      - name: run unit test
        run: npm run test:cov
        env:
          MONGODB_URL: "${{ secrets.MONGODB_URL }}"
